# Generated by Django 5.2.5 on 2025-08-07 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_paymentrequest_transaction_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number_encrypted', models.TextField()),
                ('card_holder_name', models.CharField(max_length=255)),
                ('expiry_month', models.IntegerField()),
                ('expiry_year', models.IntegerField()),
                ('cvv_encrypted', models.TextField()),
                ('card_type', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('discover', 'Discover'), ('other', 'Other')], max_length=20)),
                ('card_brand', models.CharField(max_length=50)),
                ('last_four_digits', models.CharField(max_length=4)),
                ('masked_number', models.CharField(max_length=19)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('daily_limit', models.DecimalField(decimal_places=2, default=1000.0, max_digits=15)),
                ('monthly_limit', models.DecimalField(decimal_places=2, default=5000.0, max_digits=15)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('total_funded', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Card',
                'verbose_name_plural': 'Credit Cards',
                'ordering': ['-created_at'],
            },
        ),
    ]
