# Generated by Django 5.2.5 on 2025-08-08 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='security_level',
            field=models.CharField(choices=[('basic', 'Basic'), ('enhanced', 'Enhanced'), ('maximum', 'Maximum')], default='basic', max_length=20),
        ),
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('totp', 'TOTP (Google Authenticator)')], max_length=20)),
                ('is_enabled', models.BooleanField(default=False)),
                ('secret_key', models.CharField(blank=True, help_text='TOTP secret key', max_length=255)),
                ('phone_number', models.CharField(blank=True, help_text='Phone for SMS 2FA', max_length=15)),
                ('backup_codes', models.JSONField(default=list, help_text='List of backup recovery codes')),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Two-Factor Authentication',
                'verbose_name_plural': 'Two-Factor Authentication',
            },
        ),
        migrations.CreateModel(
            name='AccountLockout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lockout_type', models.CharField(choices=[('failed_login', 'Failed Login Attempts'), ('suspicious_activity', 'Suspicious Activity'), ('admin_action', 'Admin Action'), ('security_policy', 'Security Policy Violation')], max_length=30)),
                ('reason', models.TextField()),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('locked_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('unlocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_accounts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-locked_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='userauths_a_user_id_edf224_idx'), models.Index(fields=['locked_until'], name='userauths_a_locked__c85ddf_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('2fa_enabled', '2FA Enabled'), ('2fa_disabled', '2FA Disabled'), ('2fa_used', '2FA Used'), ('2fa_failed', '2FA Failed'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked'), ('device_added', 'Device Added'), ('device_removed', 'Device Removed'), ('device_trusted', 'Device Trusted'), ('suspicious_activity', 'Suspicious Activity'), ('security_settings_changed', 'Security Settings Changed')], max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('risk_score', models.IntegerField(default=0, help_text='Risk score from 0-100')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'event_type', 'timestamp'], name='userauths_s_user_id_6000df_idx'), models.Index(fields=['ip_address', 'timestamp'], name='userauths_s_ip_addr_3970fe_idx'), models.Index(fields=['event_type', 'timestamp'], name='userauths_s_event_t_674f73_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('device_name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('operating_system', models.CharField(blank=True, max_length=100)),
                ('is_trusted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('first_used', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('user_agent', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_used'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='userauths_u_user_id_3a20f4_idx'), models.Index(fields=['device_id'], name='userauths_u_device__4c33d3_idx'), models.Index(fields=['ip_address'], name='userauths_u_ip_addr_990aa5_idx')],
            },
        ),
    ]
